import type { Metadata } from "next";
import { Asap } from '@next/font/google';
import "./globals.css";
import Navbar from './components/NavBar';
import SideNav from './components/SideNav';
import DishCard from './components/DishCard';


const asap = Asap({
  subsets: ['latin'],
  weight: ['400', '600'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={asap.className}>    
        
        {children}
        </body>
    </html>
  );
}
