import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/NavBar';
import SideNav from './components/SideNav';
import DishCard from './components/DishCard';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>    
        <div className="flex">   
        <SideNav/>
        <div className="flex flex-col ml-32">
        <Navbar/>
        <DishCard/>
        </div>
        </div>
        {children}
        </body>
    </html>
  );
}
